#!/bin/sh
# shellcheck disable=SC2034
###############################################################################
# DIRECTORIES
###############################################################################
media_dir="/cloud-storage"                              # This folder

# Cloud directories
cloud_encrypt_dir="${media_dir}/.cloud-encrypt"
cloud_decrypt_dir="${media_dir}/.cloud-decrypt"

# Local directory
local_decrypt_dir="${media_dir}/.local-decrypt/Media"

# Cache directories
cache_dir="${media_dir}/.cache"
local_cache_dir="${cache_dir}/media"
cached_media_dir="${media_dir}/mediacache"

# Media directory (FINAL)
local_media_dir="${media_dir}/media"

###############################################################################
# CLOUD CONFIG
###############################################################################
use_gdrive=1

###############################################################################
# UNION-FS
###############################################################################
ufs_dir="${media_dir}/unionfs"
ufs_bin="${ufs_dir}/unionfs"

ufs_options="-o cow,allow_other,direct_io,nonempty,auto_cache,sync_read"

###############################################################################
# PLEXDRIVE
###############################################################################
plexdrive_dir="${media_dir}/plexdrive"
plexdrive_bin="${plexdrive_dir}/plexdrive-linux-amd64"

mongo_database="plexdrive"
mongo_host="localhost"
mongo_user=""
mongo_password=""

plexdrive_temp_folder="${media_dir}/.local-decrypt/plexdrive"
plexdrive_options="--temp=${plexdrive_temp_folder} -o allow_other --clear-chunk-max-size=100G --clear-chunk-age=24h --chunk-size=10M"

###############################################################################
# RCLONE
###############################################################################
rclone_dir="${media_dir}/rclone"
rclone_bin="${rclone_dir}/rclone"

rclone_cfg="${rclone_dir}/rclone.conf"
rclone_options="--read-only --allow-non-empty --allow-other --buffer-size 500M --max-read-ahead 30G --checkers 16"

# Rclone endpoints
rclone_cloud_endpoint="gd-crypt:"
rclone_local_endpoint="local-crypt:"

###############################################################################
# SCANNER CONFIG
###############################################################################
movie_category="2"
movie_directory="storage/movies"

tv_category="3"
tv_directory="storage/tv"

###############################################################################
# MISC. CONFIG
###############################################################################
date_format="+%F@%T"
remove_files_older_than=60         # In days