#!/bin/bash

path=${1:-cloud-media-scripts}

if [[ $path == /* ]]; then
    mypwd="${path}"
else
    mypwd="$(pwd)/${path}"
fi

mypwd="${mypwd%/}"

if [ -e "${mypwd}/config" ]; then
    echo "cloud-media-scripts looks like it is already installed. Remove it or choose a different path"
    exit 02
fi

git clone "https://github.com/madslundt/cloud-media-scripts.git" "${mypwd}"

sed -i "s|INSERT_CONFIG_FILE|${mypwd}/config|g" "${mypwd}/scripts/"*
sed -i "s|INSERT_CONFIG_FILE|${mypwd}/config|g" "${mypwd}/setup.sh"
sed -i "s|INSERT_ROOT_DIR|${mypwd}|g" "${mypwd}/config"
sed -i "s|bash mount.remote|bash ${mypwd}/scripts/mount.remote|g" "${mypwd}/scripts/mountcheck"
sed -i "s|bash umount.remote|bash ${mypwd}/scripts/umount.remote|g" "${mypwd}/scripts/mountcheck"
sed -i "s|logs/|${mypwd}/logs/|g" "${mypwd}/cron"
sed -i "s|scripts/|${mypwd}/scripts/|g" "${mypwd}/cron"

echo ""
echo ""
echo "Cloud-media-scripts has been installed successfully!".
echo "Edit config file [${mypwd}/config] and run setup.sh [bash ${mypwd}/setup.sh]"
