#!/bin/sh
###############################################################################
# scanlibraries - Scan plex libraries for new files
###############################################################################

###############################################################################
# INCLUDES
###############################################################################
# shellcheck source=config

########## CONFIGURATION ##########
. "/cloud-storage/scripts/config"
###################################

###############################################################################
# CONFIGURATION
###############################################################################
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/lib/plexmediaserver"
export PLEX_MEDIA_SERVER_HOME="/usr/lib/plexmediaserver"
export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR="/var/lib/plexmediaserver/Library/Application Support"
###############################################################################
cur_exec_date=$(echo "$(date +%s)/60"|bc)

if [ ! -d "$cache_dir" ]; then
	mkdir -p "$cache_dir"
fi

if [ ! -f "${cache_dir}/lastrun" ]; then
	find_options=""
else
	prev_exec_date="$(cat "${cache_dir}/lastrun")"
	find_options="-mmin -$(echo "${cur_exec_date}" - "${prev_exec_date}" | bc)"
fi

echo "############ Movie scan started ############"
find "${movie_directory}" -mindepth 1 -type d "${find_options}" |
while read -r d; do
	echo "Scanning directory: $d"
	${PLEX_MEDIA_SERVER_HOME}/Plex\ Media\ Scanner -s -r -c "$movie_category" -d "$d"
done

echo "############## TV scan started ##############"
find "${tv_directory}" -mindepth 2 -type d "${find_options}" |
while read -r d; do
	echo "Scanning directory: $d"
	${PLEX_MEDIA_SERVER_HOME}/Plex\ Media\ Scanner -s -r -c "$tv_category" -d "$d"
done

echo "$cur_exec_date" > "${cache_dir}/lastrun"

exit
