#!/bin/bash
. "INSERT_CONFIG_FILE"

if [ -z "$(ls -A ${cloud_decrypt_dir})" ]; then
        echo "Unmount"
        bash umount.remote
        echo "Unmounted successfully"
        echo "Mount"
        bash mount.remote
        echo "Mounted successfully"
fi
