#!/bin/bash
. "INSERT_CONFIG_FILE"

if [ -z "$(ls -A ${cloud_decrypt_dir})" ]; then
        echo "[ $(date ${date_format}) ] Mount has dropped. Remount in progress."
        echo "[ $(date ${date_format}) ] Unmounting..."
        bash umount.remote
        echo "[ $(date ${date_format}) ] Unmounted successfully"
        echo "[ $(date ${date_format}) ] Mounting..."
        bash mount.remote
        echo "[ $(date ${date_format}) ] Mounted successfully"
else
        echo "[ $(date ${date_format}) ] Mount is currently up, not remounting"

fi
